#This shell file prints the file by preceeding each input line by its number and a tab character.
#usage prn.sh [file]
# ln is generated by ln.sh
chmod -w $1
ln <$1 >${1}_prn_jnk
pr -l69 ${1}_prn_jnk | lpr -Plp2
rm ${1}_prn_jnk
