#include "/home/arushi/Desktop/MajorProject/temp_pr/IRE_MajorProject/hin_morph/anusAraka/com/morph/headers/defn_kannada.h"
name_comp_offset(offset,offset_name)
int offset;
char offset_name[30];
{
switch(offset)
{
case NF1 : strcpy(offset_name,"nf1");
           break;
case NF6 : strcpy(offset_name,"nf6");
           break;
case NF8 : strcpy(offset_name,"nf8");
           break;
case NF9 : strcpy(offset_name,"nf9");
           break;
case NF19 : strcpy(offset_name,"nf19");
           break;
case NF22 : strcpy(offset_name,"nf22");
           break;
case NF23 : strcpy(offset_name,"nf23");
           break;
case NF24 : strcpy(offset_name,"nf24");
           break;
case NF39 : strcpy(offset_name,"nf39");
           break;
case NF74 : strcpy(offset_name,"nf74");
           break;
case NF76 : strcpy(offset_name,"nf76");
           break;
case NF77 : strcpy(offset_name,"nf77");
           break;
case NF78 : strcpy(offset_name,"nf78");
           break;
case NF79 : strcpy(offset_name,"nf79");
           break;
case NF80 : strcpy(offset_name,"nf80");
           break;
case NF84 : strcpy(offset_name,"nf84");
           break;
case NF85 : strcpy(offset_name,"nf85");
           break;
case NF86 : strcpy(offset_name,"nf86");
           break;
case NF89 : strcpy(offset_name,"nf89");
           break;
case NF90 : strcpy(offset_name,"nf90");
           break;
case NF104 : strcpy(offset_name,"nf104");
           break;
case NF105 : strcpy(offset_name,"nf105");
           break;
case NF106 : strcpy(offset_name,"nf106");
           break;
case NF107 : strcpy(offset_name,"nf107");
           break;
case NF110 : strcpy(offset_name,"nf110");
           break;
case NF111 : strcpy(offset_name,"nf111");
           break;
case NF117 : strcpy(offset_name,"nf117");
           break;
case NF123 : strcpy(offset_name,"nf123");
           break;
case NF124 : strcpy(offset_name,"nf124");
           break;
case NF125 : strcpy(offset_name,"nf125");
           break;
case NF126 : strcpy(offset_name,"nf126");
           break;
case NF127 : strcpy(offset_name,"nf127");
           break;
case NF128 : strcpy(offset_name,"nf128");
           break;
case NF134 : strcpy(offset_name,"nf134");
           break;
case NF140 : strcpy(offset_name,"nf140");
           break;
case NF153 : strcpy(offset_name,"nf153");
           break;
case NF179 : strcpy(offset_name,"nf179");
           break;
case NF239 : strcpy(offset_name,"nf239");
           break;
case NF241 : strcpy(offset_name,"nf241");
           break;
case NF242 : strcpy(offset_name,"nf242");
           break;
case NF253 : strcpy(offset_name,"nf253");
           break;
case NF263 : strcpy(offset_name,"nf263");
           break;
case NF266 : strcpy(offset_name,"nf266");
           break;
case NF267 : strcpy(offset_name,"nf267");
           break;
case NF269 : strcpy(offset_name,"nf269");
           break;
case NF271 : strcpy(offset_name,"nf271");
           break;
case NF281 : strcpy(offset_name,"nf281");
           break;
case NF283 : strcpy(offset_name,"nf283");
           break;
case NF284 : strcpy(offset_name,"nf284");
           break;
case NF285 : strcpy(offset_name,"nf285");
           break;
case NF291 : strcpy(offset_name,"nf291");
           break;
case NF303 : strcpy(offset_name,"nf303");
           break;
case NF312 : strcpy(offset_name,"nf312");
           break;
case NF320 : strcpy(offset_name,"nf320");
           break;
default : strcpy(offset_name,"");
		break;
}
}
