sed '1,$s/LWG_OUT_/#/g
     1,$s/_OUT_LWG//g
     1,$s/#OUT_/#/g
     1,$s/_OUT#//g
     1,$s/OUT_/#/g
     1,$s/_OUT//g
     1,$s/LWG_FRZ_/#/g
     1,$s/_FRZ_LWG//g
     1,$s/_LWG#//g
     1,$s/#LWG_//g
     1,$s/_LWG//g
     1,$s/LWG_//g
     1,$s/_FRZ#//g
     1,$s/#FRZ_//g
     1,$s/_FRZ_MO//g
     1,$s/FRZ_MO_//g
     1,$s/_FRZ//g
     1,$s/FRZ_//g
     1,$s/#_MAP//g
     1,$s/MAP_#//g
     1,$s/_MAP//g
     1,$s/MAP_//g
     1,$s/_SUF//g
     1,$s/SUF_//g
     1,$s/MO_//g
     1,$s/_MO//g
     1,$s/#_//g
     1,$s/_#//g
     1,$s/V\.//g
     1,$s/@\*#//g
     1,$s/@\*//g
     1,$s/1_\.//g
     1,$s/_%%//g
     1,$s/%%//g
     1,$s/¤//g
     1,$s/__/_/g
     1,$s/_\-_/_/g
     1,$s/_\-/-/g
     1,$s/_`/`/g'
